### ISSUE TITLE
Public page unavailable?

### ISSUE THREAD

**Issue by lemoustachiste** [w3c-ccg/vc-refresh-2021#2]
This page currently returns a 404: https://w3c-ccg.github.io/vc-refresh-2021
It is the link that's on the Readme

Where could I access the "human readable" page?

**Comment by davidlehn** [comment]
https://digitalbazaar.github.io/vc-refresh-2021/

That should updated while the repo is still here.  I think that was written assuming it would live under the ccg org.

**Comment by lemoustachiste** [comment]
Thanks @davidlehn
